package com.example.demoactiviti.mapper;

import com.example.demoactiviti.po.MhkWorkOrder;

/**
 * @author yanzhongliu
 */
public interface MhkWorkOrderMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mhk_work_order
     *
     * @mbg.generated Tue Apr 06 14:41:32 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mhk_work_order
     *
     * @mbg.generated Tue Apr 06 14:41:32 CST 2021
     */
    int insert(MhkWorkOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mhk_work_order
     *
     * @mbg.generated Tue Apr 06 14:41:32 CST 2021
     */
    int insertSelective(MhkWorkOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mhk_work_order
     *
     * @mbg.generated Tue Apr 06 14:41:32 CST 2021
     */
    MhkWorkOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mhk_work_order
     *
     * @mbg.generated Tue Apr 06 14:41:32 CST 2021
     */
    int updateByPrimaryKeySelective(MhkWorkOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mhk_work_order
     *
     * @mbg.generated Tue Apr 06 14:41:32 CST 2021
     */
    int updateByPrimaryKey(MhkWorkOrder record);
}
